//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace ChildSupport.Domain
{
    public partial class DatabaseLog
    {
        #region Primitive Properties
    
        public virtual int DatabaseLogID
        {
            get;
            set;
        }
    
        public virtual System.DateTime PostTime
        {
            get;
            set;
        }
    
        public virtual string DatabaseUser
        {
            get;
            set;
        }
    
        public virtual string Event
        {
            get;
            set;
        }
    
        public virtual string Schema
        {
            get;
            set;
        }
    
        public virtual string Object
        {
            get;
            set;
        }
    
        public virtual string TSQL
        {
            get;
            set;
        }
    
        public virtual string XmlEvent
        {
            get;
            set;
        }

        #endregion
    }
}
