//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace ChildSupport.Domain
{
    public partial class ErrorLog
    {
        #region Primitive Properties
    
        public virtual int ErrorLogID
        {
            get;
            set;
        }
    
        public virtual System.DateTime ErrorTime
        {
            get;
            set;
        }
    
        public virtual string UserName
        {
            get;
            set;
        }
    
        public virtual int ErrorNumber
        {
            get;
            set;
        }
    
        public virtual Nullable<int> ErrorSeverity
        {
            get;
            set;
        }
    
        public virtual Nullable<int> ErrorState
        {
            get;
            set;
        }
    
        public virtual string ErrorProcedure
        {
            get;
            set;
        }
    
        public virtual Nullable<int> ErrorLine
        {
            get;
            set;
        }
    
        public virtual string ErrorMessage
        {
            get;
            set;
        }

        #endregion
    }
}
