//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace ChildSupport.Domain
{
    public partial class SalesPersonQuotaHistory
    {
        #region Primitive Properties
    
        public virtual int BusinessEntityID
        {
            get { return _businessEntityID; }
            set
            {
                if (_businessEntityID != value)
                {
                    if (SalesPerson != null && SalesPerson.BusinessEntityID != value)
                    {
                        SalesPerson = null;
                    }
                    _businessEntityID = value;
                }
            }
        }
        private int _businessEntityID;
    
        public virtual System.DateTime QuotaDate
        {
            get;
            set;
        }
    
        public virtual decimal SalesQuota
        {
            get;
            set;
        }
    
        public virtual System.Guid rowguid
        {
            get;
            set;
        }
    
        public virtual System.DateTime ModifiedDate
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual SalesPerson SalesPerson
        {
            get { return _salesPerson; }
            set
            {
                if (!ReferenceEquals(_salesPerson, value))
                {
                    var previousValue = _salesPerson;
                    _salesPerson = value;
                    FixupSalesPerson(previousValue);
                }
            }
        }
        private SalesPerson _salesPerson;

        #endregion
        #region Association Fixup
    
        private void FixupSalesPerson(SalesPerson previousValue)
        {
            if (previousValue != null && previousValue.SalesPersonQuotaHistories.Contains(this))
            {
                previousValue.SalesPersonQuotaHistories.Remove(this);
            }
    
            if (SalesPerson != null)
            {
                if (!SalesPerson.SalesPersonQuotaHistories.Contains(this))
                {
                    SalesPerson.SalesPersonQuotaHistories.Add(this);
                }
                if (BusinessEntityID != SalesPerson.BusinessEntityID)
                {
                    BusinessEntityID = SalesPerson.BusinessEntityID;
                }
            }
        }

        #endregion
    }
}
