///////////////////////////////////////////////////////////
//  ISsnHighNumberStorageProvider.cs
//  Implementation of the Interface ISsnHighNumberStorageProvider
//  Generated by Enterprise Architect
//  Created on:      22-May-2008 13:19:59
//  Original author: Philippe Truche
///////////////////////////////////////////////////////////
using System.Collections.Generic;

namespace Framework.Validation.Ssn
{
    /// <summary>
    /// ISsnHighNumberStorageProvider
    /// </summary>
    public interface ISsnHighNumberStorageProvider
    {
        /// <summary>
        /// Loads the data.
        /// </summary>
        /// <returns></returns>
        IDictionary<string, byte> LoadData();
    }//end ISsnHighNumberStorageProvider

}